<?php

namespace endiorite\lobby\entity;

use pocketmine\entity\Entity;
use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\Location;
use pocketmine\entity\Skin;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\protocol\types\entity\EntityIds;

class FactionEntity extends Entity {

    public function __construct(Location $location, CompoundTag $nbt = null) {
        parent::__construct($location, $nbt);
    }

    protected function initEntity(CompoundTag $nbt): void {
        $this->setNameTagAlwaysVisible(true);
        $this->setImmobile(true);
        $this->setNameTagVisible(true);
        $this->setNameTag("§l§aFaction");
        parent::initEntity($nbt); // TODO: Change the autogenerated stub
    }

    protected function getInitialSizeInfo(): EntitySizeInfo {
        return new EntitySizeInfo(1.95, 0.6);
    }

    public static function getNetworkTypeId(): string {
        return EntityIds::VILLAGER;
    }

}