<?php

namespace endiorite\lobby\entity;

use pocketmine\entity\Entity;
use pocketmine\entity\EntitySizeInfo;
use pocketmine\nbt\tag\CompoundTag;

class FactionEntity extends Entity {

    protected function getInitialSizeInfo(): EntitySizeInfo{
        return new EntitySizeInfo(1.0, 1.0);
    }

    public static function getNetworkTypeId(): string {
        return "minecraft:villager";
    }

    protected function initEntity(CompoundTag $nbt): void {
        $this->setNameTag("§l§aFaction");
        $this->setNameTagVisible(true);
        $this->setNameTagAlwaysVisible(true);
        parent::initEntity($nbt); // TODO: Change the autogenerated stub
    }

}