<?php

namespace endiorite\entity;

use pocketmine\entity\Entity;
use pocketmine\entity\EntitySizeInfo;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\protocol\types\entity\EntityIds;

class FactionEntity extends Entity {

    protected function getInitialSizeInfo(): EntitySizeInfo{
        return new EntitySizeInfo(1.0, 1.0);
    }

    public static function getNetworkTypeId(): string {
        return "minecraft:villager";
    }

    protected function initEntity(CompoundTag $nbt): void {
        $this->setNameTag("§l§aFaction");
        parent::initEntity($nbt); // TODO: Change the autogenerated stub
    }

}